version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: DockerFile
    container_name: login-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www/
    environment:  
    - CORS_ALLOWED_ORIGINS=http://localhost:3000 
  nginx:
    image: nginx:1.25.1-alpine-slim
    container_name: login-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    image: postgres:latest
    container_name: login-db
    restart: always
    environment:
      - POSTGRES_DB=emmy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data